/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PointObjectScript")]
    [LuaRegisterType(0x83b035fed928e13d, typeof(LuaBehaviour))]
    public class PointObjectScript : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b362255d6dc7cab45b08ca3fab208faf";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Double m_ScoreIncrease = 1;
        [SerializeField] public UnityEngine.Vector3 m_moveValues = new Vector3(0f, 0f, 0f);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_ScoreIncrease),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_moveValues),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/PointObjectScript/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
